// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: image_query.sql

package db

import (
	"context"
)

const createImage = `-- name: CreateImage :one
insert into images (user_id)
values ($1)
returning id
`

func (q *Queries) CreateImage(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, createImage, userID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
