// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID             int32              `json:"id"`
	RoomID         string             `json:"room_id"`
	MessageContent string             `json:"message_content"`
	MessageOwner   int32              `json:"message_owner"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	WasDelivered   bool               `json:"was_delivered"`
}

type Room struct {
	ID         int32  `json:"id"`
	RoomUnique string `json:"room_unique"`
	User1      int32  `json:"user1"`
	User2      int32  `json:"user2"`
}

type User struct {
	ID        int32              `json:"id"`
	Username  string             `json:"username"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
