// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	ChangeDeliveryTipe(ctx context.Context, id int32) error
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllRooms(ctx context.Context) error
	GetAllExistingRooms(ctx context.Context) ([]Room, error)
	GetAllUndeliveredMessages(ctx context.Context, arg GetAllUndeliveredMessagesParams) ([]Message, error)
	GetMessagesForRoom(ctx context.Context, roomID string) ([]Message, error)
	GetRoomByUsers(ctx context.Context, arg GetRoomByUsersParams) (string, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserForLogin(ctx context.Context, arg GetUserForLoginParams) (User, error)
	GetUsersById(ctx context.Context, id int32) (User, error)
}

var _ Querier = (*Queries)(nil)
