// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRoomByUsers(ctx context.Context, arg GetRoomByUsersParams) (string, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserForLogin(ctx context.Context, arg GetUserForLoginParams) (User, error)
	GetUsersById(ctx context.Context, id int32) (User, error)
}

var _ Querier = (*Queries)(nil)
